# Generated by Django 4.2.13 on 2024-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_add_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='impressions',
            field=models.CharField(max_length=255, verbose_name='所感'),
        ),
    ]
